---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: describe_environment_health
runner_type: python-script
parameters:
  action:
    default: describe_environment_health
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  EnvironmentName:
    type: string
    description: "Specify the environment by name. You must specify either this or an EnvironmentName, or both."
  EnvironmentId:
    type: string
    description: "Specify the environment by ID. You must specify either this or an EnvironmentName, or both."
  AttributeNames:
    type: array
    description: "Specify the response elements to return. To retrieve all attributes, set to All. If no attribute names are specified, returns the name of the environment."